### ISSUE TITLE
Learn a periodic CV

### ISSUE THREAD

**Issue by HanatoK** [spiwokv/anncolvar#3]
Hi Vojtech,
I am trying to testing anncolvar to learn the CV of alanine dipeptide, and the two CVs of alanine dipeptide are periodic in the range [-pi,pi]. How can I make the training periodic aware?
Thanks!

**Comment by spiwokv** [comment]
Dear @HanatoK,
In principle it is possible to learn such CVs. The problem is their discontinuity, but neural network may learn this. I would expect such network to fail around +/- pi. It is likely to be quite inefficient, because you need many neurons and layers to cope with discontinuity. Activation functions such as RELU may improve learning. On the other hand, RELU has discontinuous derivative, which may cause artefacts. As an alternative you may use combination of sin and cos of a torsion, instead of just torsion. Hope it will help.
Vojtech

**Comment by HanatoK** [comment]
> Dear @HanatoK,
> In principle it is possible to learn such CVs. The problem is their discontinuity, but neural network may learn this. I would expect such network to fail around +/- pi. It is likely to be quite inefficient, because you need many neurons and layers to cope with discontinuity. Activation functions such as RELU may improve learning. On the other hand, RELU has discontinuous derivative, which may cause artefacts. As an alternative you may use combination of sin and cos of a torsion, instead of just torsion. Hope it will help.
> Vojtech

Thanks for your reply!
Another question is that how to learn a multi-dimensional reaction coordinate (for example the two torsion angles in alanine dipeptide). Do I need to learn the CV one by one? Or just use multiple `-col` parameters?

**Comment by spiwokv** [comment]
For Isomap we created three plumed.dat files, we changed names of functions to make them unique and we combined these plumed.dat files manually into one. Check it here:
[![plumID:19.008](https://www.plumed-nest.org/eggs/19/008/badge.svg)](https://www.plumed-nest.org/eggs/19/008/)
If there is interest in the multidimensional CVs we can prepare it for the next version.
